# Generated by Django 6.0.2 on 2026-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_vote_position_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
